<a href="[field:typelink/]" title="[field:typename/]">
        <div class="img">
          <div class="imer"><img src="/skin/images/20150812150015-83291752822697168.jpg" width="185" height="117" alt="[field:typename/]" /></div>
          <div class="bt">[field:typename/]</div>
        </div>
        <div class="info">
          <div class="imer"><img src="/skin/images/20150812150015-83291752822697168.jpg" width="185" height="117" alt="[field:typename/]" /></div>
          <div class="bta">[field:typename/]</div>
        </div>
        </a>