<div class="col-md-4 wp5"> <img src="[field:picname/]" alt="Team Member">
                <h2>[field:title/]</h2>
                <p>[field:info/]</p>
                <div class="social">
                  <ul class="social-buttons">
                    <li><a href="#" class="social-btn"><i class="fa fa-weibo"></i></a></li>
                    <li><a href="#" class="social-btn"><i class="fa fa-qq"></i></a></li>
                    <li><a href="#" class="social-btn"><i class="fa fa-envelope"></i></a></li>
                  </ul>
                </div>
              </div>