<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",390,448);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1102,1137);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",1417,1475);
$z[4][4]['name']="typeid";
$z[4][4]['function']="GetTopTypename(@me)";
$z[5]=Array("field","",1615,1673);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n        ",1726,1960);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='cu'>~typename~</a></li>";
$z[7]=Array("field","",2451,2480);
$z[7][4]['name']="typename";
$z[8]=Array("field","",2546,2575);
$z[8][4]['name']="position";
$z[9]=Array("field","",2647,2668);
$z[9][4]['name']="content";
$z[10]=Array("include","",2948,2985);
$z[10][4]['filename']="footer.htm";

?>