<?php
$z[0]=Array("field","",247,266);
$z[0][4]['name']="title";
$z[1]=Array("global","",267,293);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",334,356);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",396,447);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",3548,3567);
$z[4][4]['name']="title";
$z[5]=Array("field","",3580,3598);
$z[5][4]['name']="body";
$z[6]=Array("include","",3629,3666);
$z[6][4]['filename']="footer.htm";

?>