<li class="stmenu">
                                <div class="nav01"><a href="{dede:field name='typeurl'/}" class="xialaguang" title="{dede:field name='typename'/}"><span> {dede:field name='typename'/} </span></a></div>
                                <ul class="children clearfixmenu pngFix">
                                  {dede:channel type='son' noself='yes'}
                                  <li><a href="[field:typeurl/]" title="[field:typename/]"><span>[field:typename/]</span></a></li>
                                  {/dede:channel}
                                </ul>
                              </li>