<?php
$z[0]=Array("field","",81,109);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",137,166);
$z[1][4]['name']="typename";
$z[2]=Array("field","",175,204);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n                                  <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\"><span>[field:typename/]</span></a></li>\r\n                                  ",333,554);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>