<li>
            <div class="col-md-4 wp4">
              <div class="overlay-effect effects clearfix">
                <div class="img"> <img src="[field:picname/]" alt="[field:title/]" height="220">
                  <div class="overlay"> <a href="[field:arcurl/]" class="expand"><i class="fa fa-search"></i><br>
                    View More</a> <a class="close-overlay hidden">x</a> </div>
                </div>
              </div>
              <h2>[field:title/]</h2>
              <p>[field:info/]</p>
            </div>