<?php
$z[0]=Array("channelartlist","\r\n      <li>\r\n        <h6><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></h6>\r\n        <p> {dede:channel type='son' noself='yes'} <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> {/dede:channel} </p>\r\n      </li>\r\n      ",62,434);
$z[0][4]['typeid']="top";
$z[0][4]['row']="5";
$z[1]=Array("global","",569,593);
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",613,637);
$z[2][4]['name']="cfg_beian";

?>