<?php
$z[0]=Array("global","",136,162);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",202,228);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\r\n                              <li class=\"stmenu\">\r\n                                <div class=\"nav01\"><a href=\"{dede:field name='typeurl'/}\" class=\"xialaguang\" title=\"{dede:field name='typename'/}\"><span> {dede:field name='typename'/} </span></a></div>\r\n                                <ul class=\"children clearfixmenu pngFix\">\r\n                                  {dede:channel type='son' noself='yes'}\r\n                                  <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\"><span>[field:typename/]</span></a></li>\r\n                                  {/dede:channel}\r\n                                </ul>\r\n                              </li>\r\n                              ",1147,1897);
$z[2][4]['typeid']="top";

?>