<?php
$z[0]=Array("field","",247,266);
$z[0][4]['name']="title";
$z[1]=Array("global","",267,293);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",334,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,461);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("list","\r\n            <div class=\"col-md-4 wp4\">\r\n              <div class=\"overlay-effect effects clearfix\">\r\n                <div class=\"img\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\" height=\"220\">\r\n                  <div class=\"overlay\"> <a href=\"[field:arcurl/]\" class=\"expand\"><i class=\"fa fa-search\"></i><br>\r\n                    View More</a> <a class=\"close-overlay hidden\">x</a> </div>\r\n                </div>\r\n              </div>\r\n              <h2>[field:title/]</h2>\r\n              <p></p>\r\n            </div>\r\n            ",3657,4230);
$z[4][4]['pagesize']="27";
$z[5]=Array("include","",4301,4338);
$z[5][4]['filename']="footer.htm";

?>