<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",390,448);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1102,1137);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",1886,1944);
$z[4][4]['name']="typeid";
$z[4][4]['function']="GetTopTypename(@me)";
$z[5]=Array("field","",2084,2142);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n        ",2195,2429);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='cu'>~typename~</a></li>";
$z[7]=Array("field","",2921,2950);
$z[7][4]['name']="typename";
$z[8]=Array("field","",3016,3045);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n          <li>\r\n            <h4><a href=\"[field:arcurl/]\" title=\"[field:title/]\"></a></h4>\r\n            <div class=\"imer\"><img src=\"[field:picname/]\" width=\"218\" height=\"145\" alt=\"[field:title/]\" /></div>\r\n            <div class=\"chaw\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div>\r\n          </li>\r\n          ",3173,3549);
$z[9][4]['pagesize']="9";
$z[10]=Array("pagelist","",3661,3727);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",3831,3868);
$z[11][4]['filename']="footer.htm";

?>