<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5a6i5oi35qGI5L6L');
$cfg_Cs[2]=array(1,1,1,'5LyB5Lia6Zeo5oi3');
$cfg_Cs[3]=array(1,1,1,'55S15a2Q5ZWG5Yqh');
$cfg_Cs[4]=array(1,1,1,'5ZWG5Z+O6LSt54mp');
$cfg_Cs[5]=array(0,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[6]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[7]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[8]=array(7,1,1,'5YWs5Y+45Yqo5oCB');
$cfg_Cs[9]=array(7,1,1,'5aqS5L2T5oql6YGT');
$cfg_Cs[10]=array(7,1,1,'6KGM5Lia6LWE6K6v');
$cfg_Cs[11]=array(7,1,1,'5LiT5Lia5bi46K+G');
$cfg_Cs[12]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[14]=array(1,1,1,'5ZCE57G75bmz5Y+w');
$cfg_Cs[15]=array(1,1,1,'5paw6Ze75pS/5bqc');
?>