<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO');
$cfg_Cs[2]=array(0,2,1,'5L2c5ZOB');
$cfg_Cs[3]=array(2,2,1,'5ZOB54mM6K6+6K6h');
$cfg_Cs[4]=array(2,2,1,'5qCH5b+X6K6+6K6h');
$cfg_Cs[5]=array(2,2,1,'5YW25LuW5L2c5ZOB');
$cfg_Cs[6]=array(2,2,1,'5ZWG5Lia5o+S55S7');
$cfg_Cs[7]=array(2,2,1,'5Y2w5Yi35ZOB6K6+6K6h');
$cfg_Cs[8]=array(0,1,1,'5Y2a5a6i');
$cfg_Cs[9]=array(8,1,1,'5b+D5oOF6ZqP56yU');
$cfg_Cs[10]=array(8,1,1,'5paw5L2c6YCf6YCS');
$cfg_Cs[11]=array(8,1,1,'6K6+6K6h5p2C6LCI');
$cfg_Cs[12]=array(0,1,1,'6IGU57O7');
?>