<li class="self-link lazy-loading-item" data-ll-effect="drop-bottom"> <a href="[field:arcurl/]"> <span class="image"><img src="[field:picname/]" width="370" height="210" alt="[field:title/]" /><span class="overlay"><span class="p-icon"></span></span></span> </a>
                <div class="caption">
                      <div class="title">
                    <div class="title-hover-color"></div>
                    <div class="title-inner">
                          <div class="title-inner-content"> [field:title/] </div>
                        </div>
                  </div>
                      <div class="small-title"> [field:title/] </div>
                    </div>
              </li>