<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150905/1-150Z5103Z7.jpg ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/150905/1-150Z5103Z7.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="473";
$z[2]=Array("img"," /uploads/allimg/150905/1-150Z5103Z7-50.jpg ",238,387);
$z[2][4]['ddimg']="/uploads/allimg/150905/1-150Z5103Z7-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="800";
$z[2][4]['height']="473";
$z[3]=Array("img"," /uploads/allimg/150905/1-150Z5103Z7-51.jpg ",389,538);
$z[3][4]['ddimg']="/uploads/allimg/150905/1-150Z5103Z7-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="800";
$z[3][4]['height']="473";
$z[4]=Array("img"," /uploads/allimg/150905/1-150Z5103Z8.jpg ",540,683);
$z[4][4]['ddimg']="/uploads/allimg/150905/1-150Z5103Z8.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="800";
$z[4][4]['height']="473";
$z[5]=Array("img"," /uploads/allimg/150905/1-150Z5103Z8-50.jpg ",685,834);
$z[5][4]['ddimg']="/uploads/allimg/150905/1-150Z5103Z8-50.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="800";
$z[5][4]['height']="473";

?>