<?php
$z[0]=Array("arcurl","",245,260);
$z[1]=Array("pubdate","",279,322);
$z[1][4]['function']="MyDate('d',@me)";
$z[2]=Array("pubdate","",376,419);
$z[2][4]['function']="MyDate('m',@me)";
$z[3]=Array("arcurl","",545,560);
$z[4]=Array("title","",562,576);
$z[5]=Array("description","",673,693);
$z[6]=Array("typeurl","",866,882);
$z[7]=Array("typename","",891,909);
$z[8]=Array("typename","",911,929);
$z[9]=Array("click","",1031,1045);
$z[10]=Array("arcurl","",1075,1090);

?>