<li class="clearfix">
                    <div id="post-3888" class="post-3888 post type-post status-publish format-standard hentry category-ouluoinfo tag-71 tag-72 tag-89 tag-34">
                          <div class="comment-info"> <a href="[field:arcurl/]" class="date-day">[field:pubdate function="MyDate('d',@me)"/]</a>
                        <div class="date-month">[field:pubdate function="MyDate('m',@me)"/]</div>
                      </div>
                          <div class="post-info">
                        <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
                        <div class="text clearfix">
                              <p>[field:description/]...</p>
                            </div>
                        <div class="post-info-bottom clearfix">
                              <div class="categories"><a href="[field:typeurl/]" title="[field:typename /]">[field:typename /]</a></div>
                              <div class="comments-count"> <span class="comment-count"><b>[field:click/]</b> comments</span> <a href="[field:arcurl/]" class="more-link"><b> </b>Read more</a> </div>
                            </div>
                      </div>
                        </div>
                  </li>