<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",48,76);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",78,107);
$z[2][4]['name']="typename";
$z[3]=Array("field","",129,153);
$z[3][4]['name']="typenameen";
$z[4]=Array("channel","\r\n                <li id=\"menu-item-147\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-147\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",212,456);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>