<li class='{dede:field.currentstyle/}'><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}<br />
              {dede:field.typenameen/}</a>
              <ul class="sub-menu">
                {dede:channel type='son' noself='yes'}
                <li id="menu-item-147" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-147"><a href="[field:typeurl/]">[field:typename/]</a></li>
                {/dede:channel}
              </ul>
            </li>