<?php
$z[0]=Array("field","",208,227);
$z[0][4]['name']="title";
$z[1]=Array("global","",228,254);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",296,325);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",366,424);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",28430,28465);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",29106,29127);
$z[5][4]['name']="content";
$z[6]=Array("channel","\r\n                <li id=\"menu-item-209\" class=\"menu-item menu-item-type-post_type\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",29577,30025);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-144 current_page_item menu-item-209'><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[7]=Array("include","",30403,30440);
$z[7][4]['filename']="footer.htm";

?>