<?php
$z[0]=Array("global","",208,234);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",276,298);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",339,390);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",28666,28701);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",28994,29013);
$z[4][4]['name']="title";
$z[5]=Array("productimagelist","\r\n                <li> <a class=\"fancy_gallery\" rel=\"group-2354\" href=\"[field:imgsrc/]\"> <img src=\"[field:imgsrc/]\" > <span class=\"slide-info\"> <span class=\"slide-description\">[field:title/]</span> </span> <span class=\"overlay\"><span class=\"p-icon\"></span></span> </a> </li>\r\n                ",29442,29781);
$z[6]=Array("productimagelist","\r\n                <li> <a href=\"[field:imgsrc/]\"> <img src=\"[field:imgsrc/]\" width=\"165\" height=\"93\"/> </a> </li>\r\n                ",29941,30119);
$z[7]=Array("field","",30465,30517);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("include","",30867,30904);
$z[8][4]['filename']="footer.htm";

?>