<?php
$z[0]=Array("field","",13,41);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",43,72);
$z[1][4]['name']="typename";
$z[2]=Array("field","",98,122);
$z[2][4]['name']="typenameen";
$z[3]=Array("channel","\r\n                    <li id=\"menu-item-147\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-147\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                    ",193,445);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>