<li class="self-link classical lazy-loading-item" data-ll-effect="drop-bottom"> <a href="[field:arcurl/]"> <span class="image"><img src="[field:picname/]" width="371" height="210" alt="[field:title/]" /><span class="overlay"><span class="p-icon"></span></span></span> </a>
                    <div class="caption">
                          <div class="title">
                        <div class="title-hover-color"></div>
                        <div class="title-inner">
                              <div class="title-inner-content"> [field:title/] </div>
                            </div>
                      </div>
                          <div class="info"> [field:pubdate function="MyDate('Y-m-d',@me)"/] <span>|</span><a data-slug="classical">[field:typename/]</a> </div>
                        </div>
                  </li>