<div class="testimonial_item">
                        <table class="nostyle">
                              <tbody>
                            <tr>
                                  <td class="image"><div><img src="[field:picname/]" alt="" /></div></td>
                                  <td class="info"><span class="name">[field:title/]</span><br />
                                软装设计师：[field:title/]<br /></td>
                                </tr>
                          </tbody>
                            </table>
                        <blockquote>
                              <p>...[field:info/]</p>
                            </blockquote>
                      </div>