<?php
$z[0]=Array("global","",208,234);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",276,305);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",346,404);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",28395,28430);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",33487,33508);
$z[4][4]['name']="content";
$z[5]=Array("channel","     \r\n                <li id=\"menu-item-286\" class=\"menu-item menu-item-type-post_type\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                \r\n            ",33968,34415);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-281 current_page_item menu-item-286'><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[6]=Array("include","",34799,34836);
$z[6][4]['filename']="footer.htm";

?>