<?php
$z[0]=Array("global","",211,237);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",289,315);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",356,382);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channelartlist","\r\n            <li class='{dede:field.currentstyle/}'><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}<br />\r\n              {dede:field.typenameen/}</a>\r\n              <ul class=\"sub-menu\">\r\n                {dede:channel type='son' noself='yes'}\r\n                <li id=\"menu-item-147\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-147\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                {/dede:channel}\r\n              </ul>\r\n            </li>\r\n            ",692,1311);
$z[3][4]['typeid']="top";
$z[3][4]['row']="7";
$z[3][4]['currentstyle']="current-menu-item";

?>