<?php
$z[0]=Array("global","",223,249);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",297,327);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",368,395);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",30195,30221);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",30273,30299);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",30340,30366);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("channelartlist","\r\n                <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}<br />\r\n                  {dede:field.typenameen/}</a>\r\n                      <ul class=\"sub-menu\">\r\n                    {dede:channel type='son' noself='yes'}\r\n                    <li id=\"menu-item-147\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-147\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                    {/dede:channel}\r\n                  </ul>\r\n                    </li>\r\n                ",30868,31463);
$z[6][4]['typeid']="top";
$z[6][4]['row']="7";
$z[7]=Array("arclist","\r\n                  <li class=\"self-link lazy-loading-item\" data-ll-effect=\"drop-bottom\"> <a href=\"[field:arcurl/]\"> <span class=\"image\"><img src=\"[field:picname/]\" width=\"370\" height=\"210\" alt=\"[field:title/]\" /><span class=\"overlay\"><span class=\"p-icon\"></span></span></span> </a>\r\n                <div class=\"caption\">\r\n                      <div class=\"title\">\r\n                    <div class=\"title-hover-color\"></div>\r\n                    <div class=\"title-inner\">\r\n                          <div class=\"title-inner-content\"> [field:title/] </div>\r\n                        </div>\r\n                  </div>\r\n                      <div class=\"small-title\"> [field:title/] </div>\r\n                    </div>\r\n              </li>\r\n                  ",39146,39963);
$z[7][4]['row']="14";
$z[7][4]['titlelen']="32";
$z[7][4]['typeid']="29";
$z[7][4]['col']="3";
$z[8]=Array("arclist","\r\n                          <div class=\"testimonial_item\">\r\n                        <table class=\"nostyle\">\r\n                              <tbody>\r\n                            <tr>\r\n                                  <td class=\"image\"><div><img src=\"[field:picname/]\" alt=\"\" /></div></td>\r\n                                  <td class=\"info\"><span class=\"name\">[field:title/]</span><br />\r\n                                软装设计师：[field:title/]<br /></td>\r\n                                </tr>\r\n                          </tbody>\r\n                            </table>\r\n                        <blockquote>\r\n                              <p>...[field:info/]</p>\r\n                            </blockquote>\r\n                      </div>\r\n                          ",42547,43391);
$z[8][4]['row']="10";
$z[8][4]['titlelen']="32";
$z[8][4]['typeid']="23";
$z[8][4]['infolen']="300";
$z[9]=Array("arclist","\r\n            <div class=\"news_item lazy-loading-item clearfix\" data-ll-effect=\"fading\" onmouseout=\"this.style.background='[field:picname/]'\" style=\"cursor:pointer\" onmousemove=\"this.style.background='#DFEAE0'\" onclick=\"location.href='[field:arcurl/]';\">\r\n                  <div class=\"left-col\"> <a href=\"[field:arcurl/]\"> <img src=\"[field:picname/]\" style=\"width:105px; height:75px\" alt=\"[field:title/]\"/> <span class=\"empty\"></span> </a> </div>\r\n                  <div class=\"news-content\">\r\n                <div class=\"title\"><a class=\"colorLink\" href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n                <div class=\"text\"> 　　[field:info/]...</div>\r\n              </div>\r\n                </div>\r\n            ",44741,45537);
$z[9][4]['row']="6";
$z[9][4]['titlelen']="32";
$z[9][4]['typeid']="17";
$z[9][4]['infolen']="100";
$z[10]=Array("include","",48797,48834);
$z[10][4]['filename']="footer.htm";

?>