<?php
$z[0]=Array("global","",208,234);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",276,305);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",346,404);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",28730,28765);
$z[3][4]['filename']="head.htm";
$z[4]=Array("list","\r\n                      <li class=\"self-link classical lazy-loading-item\" data-ll-effect=\"drop-bottom\"> <a href=\"[field:arcurl/]\"> <span class=\"image\"><img src=\"[field:picname/]\" width=\"371\" height=\"210\" alt=\"[field:title/]\" /><span class=\"overlay\"><span class=\"p-icon\"></span></span></span> </a>\r\n                    <div class=\"caption\">\r\n                          <div class=\"title\">\r\n                        <div class=\"title-hover-color\"></div>\r\n                        <div class=\"title-inner\">\r\n                              <div class=\"title-inner-content\"> [field:title/] </div>\r\n                            </div>\r\n                      </div>\r\n                          <div class=\"info\"> [field:pubdate function=\"MyDate('Y-m-d',@me)\"/] <span>|</span><a data-slug=\"classical\">[field:typename/]</a> </div>\r\n                        </div>\r\n                  </li>\r\n                      ",30017,30949);
$z[4][4]['pagesize']="6";
$z[5]=Array("pagelist","",31102,31142);
$z[5][4]['listitem']="index,pageno";
$z[6]=Array("include","",31466,31503);
$z[6][4]['filename']="footer.htm";

?>