<?php
$z[0]=Array("global","",208,234);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",276,305);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",346,404);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",28368,28403);
$z[3][4]['filename']="head.htm";
$z[4]=Array("list","\r\n                <div class=\"team-element\">\r\n                      <div class=\"team-element-image\"><img src=\"[field:picname/]\" alt=\"\"/></div>\r\n                      <div class=\"team-element-name\">[field:title/]</div>\r\n                      <div class=\"team-element-position\">[field:keywords/]</div>\r\n                      <div class=\"team-element-email\"><script type=\"text/javascript\">document.write(\"<n uers=\\\"znvygb:yvaqn@byhbqrfvta.pbz\\\">Fraq Zrffntr</n>\".replace(/[a-zA-Z]/g, function(c){return String.fromCharCode((c<=\"Z\"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);}));</script></div>\r\n                    </div>\r\n                ",29103,29773);
$z[4][4]['pagesize']="20";
$z[5]=Array("include","",30122,30159);
$z[5][4]['filename']="footer.htm";

?>