<?php
$z[0]=Array("global","",208,234);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",276,305);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",346,404);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",28394,28429);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",29070,29091);
$z[4][4]['name']="content";
$z[5]=Array("channel","\r\n                <li id=\"menu-item-596\" class=\"menu-item menu-item-type-post_type\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",29542,29990);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-593 current_page_item menu-item-596'><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[6]=Array("include","",30368,30405);
$z[6][4]['filename']="footer.htm";

?>