<?php
$z[0]=Array("global","",268,294);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",424,456);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",520,552);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",617,649);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",749,784);
$z[4][4]['filename']="head.htm";
$z[5]=Array("global","",888,920);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",1086,1121);
$z[6][4]['filename']="left.htm";
$z[7]=Array("list","\r\n        <div class='ZCaseZS'><a href='[field:arcurl/]'>\r\n        <div class='ZCasePicture'><img src='[field:litpic/]' width='313' height='313' /></div>\r\n        <div class='ZCaseTitle'>\r\n          <div class='case_01'></div>\r\n          <div>[field:title/]</div>\r\n          <div class='time'>[field:pubdate function=\"MyDate('y-m-d',@me)\"/]</div>\r\n        </div>\r\n        </a></div>\r\n     ",1193,1618);
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",1701,1762);
$z[8][4]['listitem']="info,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",1825,1862);
$z[9][4]['filename']="footer.htm";

?>