<li>
            <div class='zmain_01'>
              <div class='zCRS_b'>
                <p>[field:pubdate function="MyDate('y-m-d',@me)"/]</p>
              </div>
              <div class='crs_c'><a href='[field:arcurl/]'><img src='[field:litpic/]' width='258' height='106' /></a></div>
              <div class='crs_d'><b>[field:title/]</b>
                <p>[field:description function='cn_substr(@me,58)'/]</p>
              </div>
              <div class='news_btn'><a href='[field:arcurl/]'>MORE</a></div>
            </div>
          </li>