<?php
$z[0]=Array("global","",198,230);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",307,339);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",417,449);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",749,781);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1250,1282);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1699,1731);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",2139,2171);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("channel"," <a href=\"[field:typeurl/]\">\r\n              <p> <span>[field:typenameen/]</span>[field:typename/]</p>\r\n              </a>[field:global name=autoindex runphp=\"yes\"](@me%2==0)?@me=\"\":@me=\"</li>\r\n            <li>\";[/field:global]\r\n              ",2713,3003);
$z[7][4]['type']="top";
$z[7][4]['row']="6";
$z[8]=Array("global","",3152,3184);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",3398,3430);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",3810,3836);
$z[10][4]['name']="cfg_powerby";

?>