<?php
$z[0]=Array("global","",134,166);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",350,382);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",506,538);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",708,740);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("channel","\r\n            <li><a href='[field:typeurl/]'>[field:typename/]\r\n              <p>[field:typenameen/]</p>\r\n              </a> </li>\r\n            ",1062,1413);
$z[4][4]['type']="top";
$z[4][4]['row']="5";
$z[4][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~>~typename~ <p>~typenameen~</p> </a></li>";

?>