<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",390,448);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",543,578);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",844,865);
$z[4][4]['name']="content";
$z[5]=Array("arclist"," <a href=\"#\">\r\n        <li>\r\n          <div><img src=\"[field:picname/]\" /></div>\r\n          <div class=\"block\"></div>\r\n          <div class=\"text\"><span><span>[field:title/]</span>[field:infos/]</span> </div>\r\n        </li>\r\n        </a> ",1264,1579);
$z[5][4]['typeid']="10";
$z[5][4]['row']="5";
$z[5][4]['titlelen']="30";
$z[5][4]['infolen']="100";
$z[6]=Array("global","",2355,2377);
$z[6][4]['name']="cfg_add";
$z[7]=Array("global","",2441,2463);
$z[7][4]['name']="cfg_tel";
$z[8]=Array("global","",2556,2580);
$z[8][4]['name']="cfg_email";
$z[9]=Array("include","",3963,4000);
$z[9][4]['filename']="footer.htm";

?>