<?php
$z[0]=Array("flink","  [field:link /]  ",713,792);
$z[0][4]['titlelen']="101";
$z[0][4]['row']="10";
$z[0][4]['type']="text";
$z[1]=Array("global","",899,921);
$z[1][4]['name']="cfg_add";
$z[2]=Array("global","",945,967);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",991,1015);
$z[3][4]['name']="cfg_email";
$z[4]=Array("global","",1039,1064);
$z[4][4]['name']="cfg_teltwo";
$z[5]=Array("global","",1079,1105);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",1109,1133);
$z[6][4]['name']="cfg_beian";

?>