<?php
$z[0]=Array("global","",278,305);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",343,373);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",511,537);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel"," <a href='[field:typelink/]'>\r\n      <li>[field:typename/] </li>\r\n      </a> ",1025,1150);
$z[3][4]['type']="top";
$z[3][4]['row']="5";
$z[4]=Array("type"," <a href=\"[field:typelink /]\">\r\n  <div class=\"fuwu\"> <img class=\"tubiao\" src=\"/skin/images/fuwu1.png\" /> <span>Website Building</span>\r\n    <li>网站建设</li>\r\n  </div>\r\n  </a> ",1942,2156);
$z[4][4]['typeid']="5";
$z[5]=Array("type"," <a href=\"[field:typelink /]\">\r\n  <div class=\"fuwu\"> <img class=\"tubiao\" src=\"/skin/images/fuwu2.png\" /> <span>Custom Made</span>\r\n    <li>个性定制</li>\r\n  </div>\r\n  </a> ",2160,2369);
$z[5][4]['typeid']="5";
$z[6]=Array("type"," <a href=\"[field:typelink /]\">\r\n  <div class=\"fuwu\"> <img class=\"tubiao\" src=\"/skin/images/fuwu3.png\" /> <span>Mobile Develop</span>\r\n    <li>移动开发</li>\r\n  </div>\r\n  </a> ",2373,2585);
$z[6][4]['typeid']="5";
$z[7]=Array("type"," <a href=\"[field:typelink /]\">\r\n  <div class=\"fuwu\"> <img class=\"tubiao\" src=\"/skin/images/fuwu4.png\" /> <span>Web Promotion</span>\r\n    <li>网络推广</li>\r\n  </div>\r\n  </a> ",2589,2800);
$z[7][4]['typeid']="5";
$z[8]=Array("type","\r\n  <h2>[field:typename/]</h2>\r\n  ",2973,3041);
$z[8][4]['typeid']="2";
$z[9]=Array("arclist"," <a href=\"[field:arcurl/]\">\r\n    <div class=\"tupian\"> <img src=\"[field:litpic/]\" />\r\n      <div class=\"block\"></div>\r\n      <div class=\"text\"><span>[field:title/]</span></div>\r\n    </div>\r\n    </a> ",3176,3423);
$z[9][4]['typeid']="2";
$z[9][4]['row']="8";
$z[10]=Array("type","<a href=\"[field:typeurl/]\">\r\n<div class=\"more\"></div>\r\n</a> ",3440,3534);
$z[10][4]['typeid']="2";
$z[11]=Array("arclist"," <a href=\"[field:arcurl/]\">\r\n    <div class=\"wk1\"> <img src=\"[field:litpic/]\" />\r\n      <li> <span>1.[field:title/]</span> [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]<br />\r\n        [field:infos/] </li>\r\n    </div>\r\n    </a> ",4600,4905);
$z[11][4]['typeid']="8";
$z[11][4]['row']="3";
$z[11][4]['titlelen']="30";
$z[11][4]['infolen']="100";
$z[12]=Array("type"," <a href=\"[field:typeurl/]\">\r\n<div class=\"more more1\"></div>\r\n</a> ",4922,5023);
$z[12][4]['typeid']="8";
$z[13]=Array("include","",5100,5137);
$z[13][4]['filename']="footer.htm";

?>