<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",390,448);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",529,548);
$z[3][4]['name']="title";
$z[4]=Array("global","",549,575);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("include","",679,714);
$z[5][4]['filename']="head.htm";
$z[6]=Array("type","\r\n  <h1>NEWS INFORMATION</h1>\r\n  <h2>[field:typename /]</h2>\r\n  ",774,872);
$z[6][4]['typeid']="8";
$z[7]=Array("list"," <a href=\"[field:arcurl/]\">\r\n    <div class=\"wk1\"> <img src=\"[field:picname/]\" />\r\n      <li> <span>[field:title/]</span>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</br>\r\n        [field:infos/] </li>\r\n    </div>\r\n    </a> ",1034,1309);
$z[7][4]['pagesize']="9";
$z[7][4]['infolen']="180";
$z[8]=Array("pagelist","",1372,1419);
$z[8][4]['listitem']="pageno";
$z[8][4]['listsize']="3";
$z[9]=Array("include","",1499,1536);
$z[9][4]['filename']="footer.htm";

?>