<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",390,448);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",529,548);
$z[3][4]['name']="title";
$z[4]=Array("global","",549,575);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("include","",679,714);
$z[5][4]['filename']="head.htm";
$z[6]=Array("channel"," <a href='[field:typeurl/]'>\r\n    <li >[field:typename/]</li>\r\n    </a> ",1002,1206);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a href='~typelink~' ~rel~> <li class='curr'>~typename~</li> </a>";
$z[7]=Array("list"," <a href=\"[field:arcurl/]\">\r\n      <div class=\"tupian\"> <img src=\"[field:picname/]\" />\r\n        <div class=\"block\"></div>\r\n        <div class=\"text\"><span>[field:title/]</span></div>\r\n      </div>\r\n      </a> ",1265,1510);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",1574,1621);
$z[8][4]['listitem']="pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",1714,1751);
$z[9][4]['filename']="footer.htm";

?>