<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",390,448);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",539,574);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",605,626);
$z[4][4]['name']="content";
$z[5]=Array("include","",657,694);
$z[5][4]['filename']="footer.htm";

?>