<li> <a href="[field:arcurl/]" title="[field:title/]" class="con4_img">
            <img src="[field:picname/]" width="324" height="262" alt="[field:title/]" /></a>
              <p><a href="[field:arcurl/]" title="[field:title/]">[field:title/]...</a></p>
              <div class="date">[field:pubdate function="MyDate('Y/m/d',@me)"/]</div>
              <div class="con4_view">[field:info/]...</div>
            </li>