<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150715/1-150G5154418.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150715/1-150G5154418.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="900";
$z[1][4]['height']="576";
$z[2]=Array("img"," /uploads/allimg/150715/1-150G5154418-50.jpg ",240,391);
$z[2][4]['ddimg']="/uploads/allimg/150715/1-150G5154418-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="500";
$z[2][4]['height']="391";
$z[3]=Array("img"," /uploads/allimg/150715/1-150G5154418-51.jpg ",393,544);
$z[3][4]['ddimg']="/uploads/allimg/150715/1-150G5154418-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="450";
$z[3][4]['height']="299";

?>