<dl>
            <dt><a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" width="200" height="130" alt="[field:title/]"></a></dt>
            <dd><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
              <div class="sub_news01">[field:description function='cn_substr(@me,250)'/]...</div>
              <div class="sub_news02">[field:pubdate function="MyDate('Y/m/d',@me)"/]</div>
            </dd>
          </dl>