<dl>
            <dt>
              <div class="sub_job02">[field:pubdate function="MyDate('Y/m/d',@me)"/]</div>
              <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></dt>
            <dd> [field:description function='cn_substr(@me,200)'/] ...</dd>
            <div class="sub_job01"><a href="[field:arcurl/]" title="查看更多"><img src="/skin/images/see.jpg" width="166" height="35" alt="查看更多"></a></div>
          </dl>