<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,343);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",383,434);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1943,1978);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",2353,2411);
$z[4][4]['name']="typeid";
$z[4][4]['function']="GetTopTypename(@me)";
$z[5]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            ",2478,2736);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='sider01_on'>~typename~</a></li>";
$z[6]=Array("field","",2929,2958);
$z[6][4]['name']="typename";
$z[7]=Array("field","",3011,3040);
$z[7][4]['name']="position";
$z[8]=Array("field","",3130,3149);
$z[8][4]['name']="title";
$z[9]=Array("adminname","",3200,3217);
$z[10]=Array("field","",3313,3365);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d',@me)";
$z[11]=Array("productimagelist","\r\n                  <li><a title=\"[field:text/]\">[field:title/]</a><img width=\"605\" height=\"396\" src=\"[field:imgsrc/]\" alt=\"[field:text/]\" /></li>\r\n                  ",3890,4103);
$z[12]=Array("productimagelist","\r\n                  <li  class=\"on\"><i class=\"arr2\"></i><img width=\"120\" height=\"83\" src=\"[field:imgsrc/]\" alt=\"[field:text/]\" /></li>\r\n                  ",4251,4452);
$z[13]=Array("field","",4813,4831);
$z[13][4]['name']="body";
$z[14]=Array("type","<a href=\"[field:typelink/]\" title=\"返回列表\"><img src=\"/skin/images/list.jpg\" width=\"50\" height=\"45\" alt=\"返回列表\"></a>",4912,5063);
$z[15]=Array("prenext","",5107,5132);
$z[15][4]['get']="pre";
$z[16]=Array("prenext","",5157,5183);
$z[16][4]['get']="next";
$z[17]=Array("include","",5481,5518);
$z[17][4]['filename']="footer.htm";

?>