<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,343);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",383,434);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1943,1978);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",2354,2412);
$z[4][4]['name']="typeid";
$z[4][4]['function']="GetTopTypename(@me)";
$z[5]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            ",2479,2737);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='sider01_on'>~typename~</a></li>";
$z[6]=Array("field","",2930,2959);
$z[6][4]['name']="typename";
$z[7]=Array("field","",3012,3041);
$z[7][4]['name']="position";
$z[8]=Array("field","",3131,3150);
$z[8][4]['name']="title";
$z[9]=Array("adminname","",3200,3217);
$z[10]=Array("field","",3312,3364);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d',@me)";
$z[11]=Array("field","",3407,3425);
$z[11][4]['name']="body";
$z[12]=Array("type","<a href=\"[field:typelink/]\" title=\"返回列表\"><img src=\"/skin/images/list.jpg\" width=\"50\" height=\"45\" alt=\"返回列表\"></a>",3506,3657);
$z[13]=Array("prenext","",3701,3726);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",3751,3777);
$z[14][4]['get']="next";
$z[15]=Array("include","",4075,4112);
$z[15][4]['filename']="footer.htm";

?>