<?php
$z[0]=Array("global","",168,194);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> ",229,345);
$z[1][4]['type']="top";
$z[2]=Array("global","",427,453);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",478,500);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",509,530);
$z[4][4]['name']="cfg_cz";
$z[5]=Array("global","",540,564);
$z[5][4]['name']="cfg_email";
$z[6]=Array("global","",667,691);
$z[6][4]['name']="cfg_beian";

?>