<?php
$z[0]=Array("global","",295,321);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",374,400);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\r\n        <li><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\" >{dede:field name='typename'/}</a>\r\n          <dl>\r\n            {dede:channel type='son' noself='yes'}\r\n            <dd><a href=\"[field:typelink/]\"  title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n            {/dede:channel}\r\n          </dl>\r\n        </li>\r\n        ",442,861);
$z[2][4]['typeid']="top";

?>