<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",390,448);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1959,1994);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",2370,2428);
$z[4][4]['name']="typeid";
$z[4][4]['function']="GetTopTypename(@me)";
$z[5]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            ",2495,2753);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='sider01_on'>~typename~</a></li>";
$z[6]=Array("field","",2946,2975);
$z[6][4]['name']="typename";
$z[7]=Array("field","",3028,3057);
$z[7][4]['name']="position";
$z[8]=Array("field","",4128,4149);
$z[8][4]['name']="content";
$z[9]=Array("include","",4616,4653);
$z[9][4]['filename']="footer.htm";

?>