<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5pyN5Yqh6IyD5Zu0');
$cfg_Cs[2]=array(0,2,1,'57uP5YW45qGI5L6L');
$cfg_Cs[3]=array(2,2,1,'5LyB5Lia6Zeo5oi3');
$cfg_Cs[4]=array(2,2,1,'55S15a2Q5ZWG5Yqh');
$cfg_Cs[5]=array(2,2,1,'5ZWG5Z+O6LSt54mp');
$cfg_Cs[6]=array(2,2,1,'5ZCE57G75bmz5Y+w');
$cfg_Cs[7]=array(2,2,1,'5paw6Ze75pS/5bqc');
$cfg_Cs[8]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[9]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[10]=array(0,1,1,'57uP6JCl5Zui6Zif');
?>