<div class="list">
      <div class="l_left"> <a href="[field:arcurl/]"><img src="[field:picname/]" width="180" height="130" /></a> </div>
      <div class="l_right">
        <h2><em>[field:pubdate function="MyDate('Y-m-d',@me)"/]</em><a href="[field:arcurl/]">[field:title/]</a></h2>
        <p>[field:description function="cn_substr(@me,300)"/]...<a href="[field:arcurl/]">查看详细>></a></p>
      </div>
      <div style="clear:both"></div>
    </div>