<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,343);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",383,434);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",452,479);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("include","",1169,1204);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1587,1606);
$z[5][4]['name']="title";
$z[6]=Array("field","",1659,1715);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[7]=Array("field","",1751,1769);
$z[7][4]['name']="body";
$z[8]=Array("include","",1900,1937);
$z[8][4]['filename']="footer.htm";

?>