<?php
$z[0]=Array("global","",66,92);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",133,162);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",202,260);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",278,305);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("include","",499,534);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",736,794);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel"," <a href='[field:typeurl/]' ><i></i>[field:typename/]<span></span></a> ",836,1035);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a href='~typelink~' class='active'><i></i>~typename~<span></span></a>";
$z[7]=Array("field","",1083,1104);
$z[7][4]['name']="content";
$z[8]=Array("include","",1121,1158);
$z[8][4]['filename']="footer.htm";

?>