<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",390,448);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",466,493);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("include","",1114,1149);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n      <li><a href='[field:typeurl/]' >[field:typename/]</a></li>\r\n      ",1436,1644);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='thistab'><a href='~typelink~'>~typename~</a></li>";
$z[6]=Array("list","\r\n          <li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"335\" height=\"244\" /></a>\r\n            <div class=\"text31\"> <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n              <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n            </div>\r\n          </li>\r\n          ",1747,2089);
$z[6][4]['pagesize']="6";
$z[7]=Array("pagelist","",2175,2245);
$z[7][4]['listitem']="info,index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2928,2965);
$z[8][4]['filename']="footer.htm";

?>