<?php
$z[0]=Array("global","",228,254);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",295,317);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",357,408);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",659,694);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel","\r\n      <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",982,1186);
$z[4][4]['type']="son";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class='select'>~typename~</a></li>";
$z[5]=Array("field","",1282,1311);
$z[5][4]['name']="typename";
$z[6]=Array("field","",1344,1373);
$z[6][4]['name']="position";
$z[7]=Array("field","",1618,1637);
$z[7][4]['name']="title";
$z[8]=Array("field","",1964,1982);
$z[8][4]['name']="body";
$z[9]=Array("include","",2108,2145);
$z[9][4]['filename']="footer.htm";

?>