<?php
$z[0]=Array("field","",228,247);
$z[0][4]['name']="title";
$z[1]=Array("global","",248,274);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",315,344);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",384,442);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",693,728);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n      <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",1016,1220);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='select'>~typename~</a></li>";
$z[6]=Array("field","",1316,1345);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1378,1407);
$z[7][4]['name']="position";
$z[8]=Array("field","",1517,1538);
$z[8][4]['name']="content";
$z[9]=Array("include","",1594,1631);
$z[9][4]['filename']="footer.htm";

?>