<?php
$z[0]=Array("global","",228,254);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",298,328);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",365,392);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",702,737);
$z[3][4]['filename']="head.htm";
$z[4]=Array("type","<a href=\"[field:typelink/]\"><img src=\"/skin/images/more.png\" width=\"62\" height=\"62\" /></a> ",1596,1721);
$z[4][4]['typeid']="1";
$z[5]=Array("arclist","\r\n    <li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"237\" height=\"237\" /></a><i><a href=\"[field:arcurl/]\">-[field:title/]-</a></i></li>\r\n    ",1860,2077);
$z[5][4]['row']="4";
$z[5][4]['titlelen']="32";
$z[5][4]['typeid']="8";
$z[6]=Array("type","<a href=\"[field:typelink/]\">更多产品</a>",2109,2187);
$z[6][4]['typeid']="8";
$z[7]=Array("type","<a href=\"[field:typelink/]\">READ MORE</a>",2293,2368);
$z[7][4]['typeid']="5";
$z[8]=Array("arclist","\r\n    <li>\r\n      <div class=\"date\"><span class=\"day\">[field:pubdate function=\"MyDate('d',@me)\"/]</span><span class=\"month\">[field:pubdate function=\"MyDate('m',@me)\"/]</span></div>\r\n      <div class=\"newscon\"><a href=\"/a/xinwenzixun/gongsixinwen/2015/0529/12.html\">\r\n        <h2>[field:title/]</h2>\r\n        <p>[field:info/]...</p>\r\n        </a></div>\r\n    </li>\r\n    ",2504,2944);
$z[8][4]['infolen']="60";
$z[8][4]['row']="4";
$z[8][4]['titlelen']="32";
$z[8][4]['typeid']="11";
$z[9]=Array("include","",2992,3029);
$z[9][4]['filename']="footer.htm";

?>