<?php
$z[0]=Array("global","",228,254);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",295,324);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",364,422);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",673,708);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel","\r\n      <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",1005,1209);
$z[4][4]['type']="son";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class='select'>~typename~</a></li>";
$z[5]=Array("field","",1315,1344);
$z[5][4]['name']="typename";
$z[6]=Array("field","",1379,1408);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n          <li><a href=\"[field:arcurl/]\">[field:title/]</a><i>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</i></li>\r\n         ",1752,1918);
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",1994,2047);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("include","",2124,2161);
$z[9][4]['filename']="footer.htm";

?>