<?php
$z[0]=Array("pubdate","",125,171);
$z[0][4]['function']="MyDate('Y年',@me)";
$z[1]=Array("pubdate","",189,234);
$z[1][4]['function']="MyDate('m-d',@me)";
$z[2]=Array("arcurl","",311,326);
$z[3]=Array("title","",335,349);
$z[4]=Array("title","",351,365);
$z[5]=Array("description","",408,458);
$z[5][4]['function']="cn_substr(@me,250)";
$z[6]=Array("arcurl","",470,485);
$z[7]=Array("title","",494,508);

?>