<li>
          <div class="mosaic-block bar"> <a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="mosaic-overlay">
            <div class="details">[field:title/]</div>
            </a>
            <div class="mosaic-backdrop"><a href="[field:arcurl/]" title="[field:title/]" target="_blank"><img src="[field:picname/]" alt="[field:title/]"/></a></div>
          </div>
        </li>