　
        <article>
          <div class="citem"><a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" alt="[field:title/]" class="attachment-post-thumbnail wp-post-image" /> <span></span> </a>
            <div class="citemtxt"><a href="[field:arcurl/]" title="[field:title/]">
              <h4>[field:title/]</h4>
              </a>
              <p><span><a href='[field:typeurl/]'>[field:typename/]</a></span><em>
                <label>[field:click/]</label>
                浏览</em> </p>
            </div>
          </div>
        </article>