<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1010,1045);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","\r\n        <li class=\"cat-item cat-item-2\"><a href='[field:typelink/]'>所有</a></li>\r\n        ",1170,1299);
$z[5][4]['typeid']="1";
$z[6]=Array("channel","\r\n        <li class=\"cat-item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",1309,1541);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[7]=Array("list","\r\n      <article>\r\n        <div class=\"citem\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\" class=\"attachment-post-thumbnail wp-post-image\" /> <span></span> </a>\r\n          <div class=\"citemtxt\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n            <h4>[field:title/]</h4>\r\n            </a>\r\n            <p><span><a href='[field:typeurl/]'>[field:typename/]</a></span><em>\r\n              <label>[field:click/]</label>\r\n              浏览</em> </p>\r\n          </div>\r\n        </div>\r\n      </article>\r\n      ",1716,2323);
$z[7][4]['pagesize']="8";
$z[8]=Array("pagelist","",2402,2455);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("include","",2671,2708);
$z[9][4]['filename']="footer.htm";

?>