<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1010,1045);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type"," <a href=\"[field:typelink/]\" class=\"contact-btn1\">欣赏案例 ></a>",3557,3659);
$z[5][4]['typeid']="1";
$z[6]=Array("type"," <a href=\"[field:typelink/]\" class=\"contact-btn1\">欣赏案例 ></a>",4101,4203);
$z[6][4]['typeid']="1";
$z[7]=Array("include","",7010,7047);
$z[7][4]['filename']="footer.htm";

?>