<article class="post-format-standard">
                  <div class="wf-td"><a class="alignleft post-rollover" href="[field:arcurl/]" ><img class="preload-me" src="[field:picname/]" width="60" height="60"  alt="flash" /></a></div>
                  <div class="post-content"><a href="[field:arcurl/]">[field:title/]</a><br />
                    <time class="text-secondary" >[field:pubdate function="MyDate('Y年m月d日',@me)"/]</time>
                  </div>
                </article>