<?php
$z[0]=Array("title","",41,55);
$z[1]=Array("arcurl","",245,260);
$z[2]=Array("picname","",319,335);
$z[3]=Array("title","",342,356);
$z[4]=Array("title","",365,379);
$z[5]=Array("arcurl","",545,560);
$z[6]=Array("title","",569,583);
$z[7]=Array("title","",600,614);
$z[8]=Array("description","",777,797);
$z[9]=Array("arcurl","",920,935);
$z[10]=Array("pubdate","",999,1053);
$z[10][4]['function']="MyDate('Y年m月d日',@me)";
$z[11]=Array("arcurl","",1121,1136);

?>