<div class="wf-cell iso-item" data-name="[field:title/]">
              <article class="post type-post status-publish format-standard hentry category-about-design">
                <div class="blog-media wf-td">
                  <p><a href="[field:arcurl/]" class="alignnone rollover" ><img class="preload-me" src="[field:picname/]" alt="[field:title/]" title="[field:title/]" width="270" height="270"  /></a></p>
                </div>
                <div class="blog-content wf-td">
                  <h2 class="entry-title"> <a href="[field:arcurl/]" title="[field:title/]" rel="bookmark">[field:title/]</a> </h2>
                  <div class="entry-meta"><a href='/web10/a/boke/xinqingsuibi/'>心情随笔</a></div>
                  <p style="text-align: left;">[field:description/]...</p>
                  <p style="text-align: center;">
                  <div class="post-format entry-meta"><a href="[field:arcurl/]" rel="bookmark">
                    <time class="entry-date">[field:pubdate function="MyDate('Y年m月d日',@me)"/]</time>
                    </a></div>
                  <a href="[field:arcurl/]" class="details more-link" rel="nofollow">详情</a> </div>
              </article>
              <!-- #post-14147 --> 
              
            </div>