<li class="fs-entry ts-cell">
                  <div class="fs-entry-slide">
                    <div class="fs-entry-img"> <img src="[field:picname/]" class="preload-me" width="210" height="210"  alt="[field:title/]" /></div>
                    <div class="fs-entry-content">
                      <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
                      <div class="portfolio-categories"><a href="[field:arcurl/]" rel="bookmark">
                        <time class="entry-date" >{dede:field.pubdate function="MyDate('Y年m月d日',@me)"/}</time>
                        </a><a class="author vcard" href="[field:arcurl/]" rel="author">By admin</a><a href='/web10/a/zuopin/shangyechahua/'>商业插画</a></div>
                      <a class="project-details" href="[field:arcurl/]">详情</a> </div>
                  </div>
                </li>