<?php
$z[0]=Array("arcurl","",211,226);
$z[1]=Array("picname","",430,446);
$z[2]=Array("arcurl","",947,962);
$z[3]=Array("title","",971,985);
$z[4]=Array("title","",1002,1016);
$z[5]=Array("arcurl","",1154,1169);
$z[6]=Array("writer","",1187,1202);
$z[7]=Array("arcurl","",1248,1263);
$z[8]=Array("title","",1305,1319);
$z[9]=Array("typelink","",1321,1338);
$z[10]=Array("info","",1373,1386);
$z[11]=Array("arcurl","",1523,1538);
$z[12]=Array("pubdate","",1604,1651);
$z[12][4]['function']="MyDate('Y-m-d',@me)";

?>