<li class="fs-entry ts-cell" style="width: 230px; opacity: 1; left: 230px;">
            <div class="fs-entry-slide"><div class="fs-entry-img blur-this blur-ready" data-dt-link="[field:arcurl/]"><canvas width="210" height="210" title="" class="preload-me blur-effect" tabindex="-1" id=""></canvas>
		<img src="[field:picname/]" class="preload-me" width="210" height="210" alt="[field:title/]" data-bd-imgshare-binded="1"><i></i></div>
		<div class="fs-entry-content" style="opacity: 1;">
			<h4><a href="[field:arcurl/]">[field:title/]</a></h4>
			<div class="portfolio-categories"><a href="[field:arcurl/]" title="下午 5:07" rel="bookmark"><time class="entry-date" datetime="2014-05-02T17:07:59+00:00">{dede:field.pubdate function="MyDate('Y年m月d日',@me)"/}</time></a><a class="author vcard" href="[field:arcurl/]" title="[field:title/]" rel="author">By admin</a><a href="[field:arcurl/]">读书沙龙</a></div><a class="project-details" href="[field:arcurl/]">详情</a>
		</div>
	</div></li>