<?php
$z[0]=Array("arcurl","",217,232);
$z[1]=Array("picname","",436,452);
$z[2]=Array("arcurl","",959,974);
$z[3]=Array("title","",983,997);
$z[4]=Array("title","",1014,1028);
$z[5]=Array("arcurl","",1168,1183);
$z[6]=Array("adminname","",1201,1219);
$z[7]=Array("arcurl","",1265,1280);
$z[8]=Array("typelink","",1360,1377);
$z[9]=Array("info","",1414,1427);
$z[10]=Array("arcurl","",1568,1583);
$z[11]=Array("pubdate","",1651,1698);
$z[11][4]['function']="MyDate('Y-m-d',@me)";

?>