<?php
$z[0]=Array("arcurl","",211,226);
$z[1]=Array("picname","",430,446);
$z[2]=Array("arcurl","",947,962);
$z[3]=Array("title","",971,985);
$z[4]=Array("title","",1002,1016);
$z[5]=Array("arcurl","",1154,1169);
$z[6]=Array("writer","",1187,1202);
$z[7]=Array("arcurl","",1248,1263);
$z[8]=Array("typelink","",1343,1360);
$z[9]=Array("info","",1395,1408);
$z[10]=Array("arcurl","",1545,1560);
$z[11]=Array("pubdate","",1626,1673);
$z[11][4]['function']="MyDate('Y-m-d',@me)";

?>