<?php
$z[0]=Array("global","",653,679);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",720,742);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",782,833);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",5369,5404);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",5557,5576);
$z[4][4]['name']="title";
$z[5]=Array("field","",5845,5874);
$z[5][4]['name']="position";
$z[6]=Array("field","",6354,6372);
$z[6][4]['name']="body";
$z[7]=Array("field","",6542,6601);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y年m月d日',@me)";
$z[8]=Array("adminname","",6677,6694);
$z[9]=Array("type","<a href=\"[field:typelink /]\" >[field:typename /]</a>",6699,6774);
$z[10]=Array("channel","\r\n              <li class=\"cat-item\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n              ",7643,7929);
$z[10][4]['type']="son";
$z[10][4]['currentstyle']="<li><a href='~typelink~' class='show-all act'>~typename~</a></li>";
$z[11]=Array("arclist","\r\n                <article class=\"post-format-standard\">\r\n                  <div class=\"wf-td\"><a class=\"alignleft post-rollover\" href=\"[field:arcurl/]\" ><img class=\"preload-me\" src=\"[field:picname/]\" width=\"60\" height=\"60\"  alt=\"flash\" /></a></div>\r\n                  <div class=\"post-content\"><a href=\"[field:arcurl/]\">[field:title/]</a><br />\r\n                    <time class=\"text-secondary\" >[field:pubdate function=\"MyDate('Y年m月d日',@me)\"/]</time>\r\n                  </div>\r\n                </article>\r\n                ",8180,8768);
$z[11][4]['titlelen']="42";
$z[11][4]['row']="6";
$z[11][4]['typeid']="8";
$z[12]=Array("include","",8981,9018);
$z[12][4]['filename']="footer.htm";

?>