<?php
$z[0]=Array("field","",653,672);
$z[0][4]['name']="title";
$z[1]=Array("global","",673,699);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",740,762);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",802,853);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",5389,5424);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",5577,5596);
$z[5][4]['name']="title";
$z[6]=Array("field","",5865,5894);
$z[6][4]['name']="position";
$z[7]=Array("field","",6374,6392);
$z[7][4]['name']="body";
$z[8]=Array("field","",6562,6621);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y年m月d日',@me)";
$z[9]=Array("adminname","",6697,6714);
$z[10]=Array("type","<a href=\"[field:typelink /]\" >[field:typename /]</a>",6719,6794);
$z[11]=Array("channel","\r\n              <li class=\"cat-item\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n              ",7663,7949);
$z[11][4]['type']="son";
$z[11][4]['currentstyle']="<li><a href='~typelink~' class='show-all act'>~typename~</a></li>";
$z[12]=Array("arclist","\r\n                <article class=\"post-format-standard\">\r\n                  <div class=\"wf-td\"><a class=\"alignleft post-rollover\" href=\"[field:arcurl/]\" ><img class=\"preload-me\" src=\"[field:picname/]\" width=\"60\" height=\"60\"  alt=\"flash\" /></a></div>\r\n                  <div class=\"post-content\"><a href=\"[field:arcurl/]\">[field:title/]</a><br />\r\n                    <time class=\"text-secondary\" >[field:pubdate function=\"MyDate('Y年m月d日',@me)\"/]</time>\r\n                  </div>\r\n                </article>\r\n                ",8200,8788);
$z[12][4]['titlelen']="42";
$z[12][4]['row']="6";
$z[12][4]['typeid']="8";
$z[13]=Array("include","",9001,9038);
$z[13][4]['filename']="footer.htm";

?>