<?php
$z[0]=Array("title","",41,55);
$z[1]=Array("arcurl","",245,260);
$z[2]=Array("picname","",319,335);
$z[3]=Array("title","",342,356);
$z[4]=Array("title","",365,379);
$z[5]=Array("arcurl","",545,560);
$z[6]=Array("title","",569,583);
$z[7]=Array("title","",600,614);
$z[8]=Array("description","",777,827);
$z[8][4]['function']="cn_substr(@me,170)";
$z[9]=Array("arcurl","",950,965);
$z[10]=Array("pubdate","",1029,1083);
$z[10][4]['function']="MyDate('Y年m月d日',@me)";
$z[11]=Array("arcurl","",1151,1166);

?>