<?php
$z[0]=Array("arcurl","",217,232);
$z[1]=Array("picname","",436,452);
$z[2]=Array("arcurl","",959,974);
$z[3]=Array("title","",983,997);
$z[4]=Array("title","",1014,1028);
$z[5]=Array("arcurl","",1168,1183);
$z[6]=Array("arcurl","",1267,1282);
$z[7]=Array("typelink","",1362,1379);
$z[8]=Array("info","",1416,1429);
$z[9]=Array("arcurl","",1570,1585);
$z[10]=Array("pubdate","",1653,1700);
$z[10][4]['function']="MyDate('Y-m-d',@me)";

?>