<?php
$z[0]=Array("myad","",446,468);
$z[0][4]['name']="bz";
$z[1]=Array("myad","",642,664);
$z[1][4]['name']="pp";
$z[2]=Array("myad","",841,863);
$z[2][4]['name']="ys";
$z[3]=Array("myad","",1037,1059);
$z[3][4]['name']="sy";
$z[4]=Array("arclist","\r\n              <li><a href=\"[field:arcurl/]\" style=\"text-decoration: none\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]  [field:title/]</a></li>\r\n              ",1821,2045);
$z[4][4]['row']="9";
$z[4][4]['titlelen']="40";
$z[4][4]['typeid']="8";
$z[5]=Array("flink","\r\n          <li>[field:link /]</li>\r\n          ",2278,2385);
$z[5][4]['titlelen']="20";
$z[5][4]['row']="10";
$z[5][4]['type']="text";
$z[6]=Array("global","",2949,2975);
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("global","",3052,3076);
$z[7][4]['name']="cfg_beian";

?>