<?php
$z[0]=Array("global","",323,345);
$z[0][4]['name']="cfg_tel";
$z[1]=Array("channel","\r\n          <li class=\"menu-item menu-item-type-post_type menu-item-object-page menu-frame-on level-arrows-on\"><a href='[field:typeurl/]' ><span>[field:typename/]</span></a></li>\r\n          ",2118,2611);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<li class='menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item level-arrows-on current_page_item act first menu-frame-on'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>