<?php
$z[0]=Array("global","",653,679);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",720,749);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",789,847);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",4686,4721);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",5474,5503);
$z[4][4]['name']="position";
$z[5]=Array("field","",7023,7044);
$z[5][4]['name']="content";
$z[6]=Array("include","",7515,7552);
$z[6][4]['filename']="footer.htm";

?>