<?php
$z[0]=Array("global","",84,110);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",155,177);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",221,272);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",505,534);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",599,628);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",713,742);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",815,844);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("global","",896,925);
$z[7][4]['name']="cfg_templeturl";
$z[8]=Array("global","",980,1009);
$z[8][4]['name']="cfg_templeturl";
$z[9]=Array("global","",1164,1193);
$z[9][4]['name']="cfg_templeturl";
$z[10]=Array("global","",1300,1329);
$z[10][4]['name']="cfg_templeturl";
$z[11]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",1577,1799);
$z[11][4]['type']="top";
$z[11][4]['currentstyle']="<li class='active'><a href='~typelink~' style='color:white;'>~typename~</a></li>";
$z[12]=Array("channel","\r\n        	 <a href=\"[field:typeurl/]\" class=\"btn btn-default\">[field:typename/]</a>\r\n             ",2405,2631);
$z[12][4]['type']="son";
$z[12][4]['currentstyle']="<a href='~typelink~' class='btn btn-default btn-primary'>~typename~</a>";
$z[13]=Array("list","\r\n        	<li>\r\n              <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n              <img src=\"[field:litpic/]\" alt=\"[field:title/]\" />\r\n              <p>网站设计<br /><strong>[field:title/]</strong><br />[field:id function=GetTags(@me)/]</p></a>\r\n            </li>\r\n           ",2764,3087);
$z[13][4]['pagesize']="12";
$z[14]=Array("pagelist","",3205,3261);
$z[14][4]['listitem']="pre,next,pageno";
$z[14][4]['listsize']="5";

?>