<?php
$z[0]=Array("global","",342,371);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",436,465);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",525,554);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",635,664);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",737,766);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",818,847);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",951,980);
$z[6][4]['name']="cfg_templeturl";

?>