<?php
$z[0]=Array("global","",360,389);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",454,483);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",568,597);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",670,699);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",748,777);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",901,930);
$z[5][4]['name']="cfg_templeturl";

?>